### ISSUE TITLE
Status FAILED

### ISSUE THREAD

**Issue by mbalance** [DigixGlobal/etc-redemption#1]
Why is the execution failing?

https://gastracker.io/tx/0x0ff7f1cd0005db31f1d86c101a732ca90e2a16fc43bad2f3a02ba40a70d50551

**Comment by hitchcott** [comment]
Hi, The address that sent the transaction is not a DGD holder

https://etherscan.io/address/0xDBe17B408aFc37EEf20271228fC50d5e1F16814F

So it does not have a DGDR balance, therefore the transaction is failing.

**Comment by mbalance** [comment]
Ok thanks, I thought so but I wasn't sure
